sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t8QLFHmuE3E5UjtcWwC
    access-key-secret:
    bucket-name: wk-take-out
  redis:
    host: localhost
    port: 6379

